trigger:
 - main

 pool:
 vmImage: local

 variables:
 repositoryName: 'nikolajacques/learning'

 steps:
 - task: Docker@2
 inputs:
 containerRegistry: 'docker-hub-connection-learning'
 repository: $(repositoryName)
 command: 'buildAndPush'
 Dockerfile: '**/Dockerfile'
