trigger:
 - main

pool: Default

variables:
  repositoryName: 'nikolajacques/learning'

steps:
 - task: Docker@2
   inputs:
        containerRegistry: 'docker-hub-connection-learning'
        repository: $(repositoryName)
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
